### ISSUE TITLE
Sample bias of the dataset

### ISSUE THREAD

**Issue by jiqicn** [EyeofBeholder-NLeSC/play-around-sample-set#2]
There might be sample bias on the worker profile data, which means that there are more instances with one specific value of a feature than the other values, and the dataset is multivariate. Need to find a way to reduce the effect of this sample bias.

**Comment by jiqicn** [comment]
This [notebook](https://github.com/EyeofBeholder-NLeSC/play-around-sample-set/blob/main/notebooks/IPM_worker_profile.ipynb) contains relevant statistics.

**Comment by jiqicn** [comment]
Not a problem for now, but could be in the future. It's also not handy to do oversampling on the dataset due to its small size. It can also be foreseen that there won't be a future dataset of a large number of workers.

**Comment by davideceolin** [comment]
There is some bias in terms of the workers' population. The bias that
different classes of workers have when evaluating quality is, instead,
limited.

Il giorno lun 21 mar 2022 alle ore 09:55 Ji Qi ***@***.***>
ha scritto:
